name = "c0desk1-00"
compatibility_date = "2026-05-08"
compatibility_flags = ["global_fetch_strictly_public"]
main = "@astrojs/cloudflare/entrypoints/server"

[vars]
API_URL = "https://api.c0desk1.my.id/"
ADMIN_TOKEN = "awokawok_atmin"